#!/bin/bash
curl -sLo manifest-tool "https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64"
chmod +x manifest-tool
sed -e "s#%image_name%#${IMAGE_NAME%%-*}#" manifest.template > manifest.yaml
set +e
./manifest-tool push from-spec manifest.yaml
if [ $? -ne 0 ]; then
  echo "manifest failed, post_push step ignored"
  exit 0
fi
